import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavigationMenuDemo } from "@/components/navigation";
import Nav from "@/components/nav";
import Tags from "@/components/Tags";
import Loader from "@/components/loader";
import { SessionProvider } from "next-auth/react";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Loader />

          <main>{children}</main>
        </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
