import Nav from '@/components/nav'
import ProfileNav from '@/components/profileNav'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import { auth } from '@/lib/auth'
import clsx from 'clsx'
import { Metadata } from 'next'
import Link from 'next/link'
import { redirect,} from 'next/navigation'
import React, { Children } from 'react'


export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

const page =async  (props: any)  => {
    const session = await auth()
    if(!session?.user) redirect("/auth")
    
  return (
    <div className='container mx-auto'>
      {/* {JSON.stringify(props)} */}
        <Nav/>
        <div className="w-full  flex flex-row items-center p-8">
        <Avatar className="w-24 h-24 border-2 border-secondary-foreground">
            {session.user.image && (
              <AvatarImage className=''
                src={session.user.image}
                alt={session.user.name?.slice(0,2) ?? ""}
              />
            )}
            <AvatarFallback>{session.user.email}</AvatarFallback>
          </Avatar>
            <h1 className='text-3xl pl-5'>{session.user.name}</h1>
        </div>
        <ProfileNav/>
        {
          props.children
        }
    </div>
  )
}

export default page